run smoke tests

diff --git a/.github/workflows/arcgis-learn-test.yaml b/.github/workflows/arcgis-learn-test.yaml
--- a/.github/workflows/arcgis-learn-test.yaml
+++ b/.github/workflows/arcgis-learn-test.yaml
@@ -31,9 +31,13 @@ jobs:
           pwd
 
           echo "Setting up required environment variables"
-          WORKSPACE=pwd
-          export LC_ALL=en_US.UTF-8; export LC_CTYPE=en_US.UTF-8;
-          export run_nightly=0; export run_inference=0; export run_weekly=0; export run_backbones=0;
+          WORKSPACE=$(pwd)
+          export LC_ALL=en_US.UTF-8
+          export LC_CTYPE=en_US.UTF-8
+          export run_nightly=0
+          export run_inference=0
+          export run_weekly=0
+          export run_backbones=0
           export PYTHONPATH="$WORKSPACE/tests"
           SMOKE_DIR="$WORKSPACE/tests/smoke"
 
@@ -42,7 +46,12 @@ jobs:
           for test_file in "$SMOKE_DIR"/*.py; do
             $PYTHON "$test_file"
             exit_code=$?
-          
+            if [ $exit_code -ne 0 ]; then
+              echo "Test Failed: $test_file"
+              exit $exit_code
+            Fi
+          done
+                    
           echo "All smoke tests passed."
           echo "======================================="
           
