conda build --test, annotate build with warning, skip pip check on windows

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -71,11 +71,14 @@ jobs:
         run: |
           conda build arcgis --override-channels -c esri -c esri-build -c defaults --python ${{ matrix.python }} --package-format .conda --output-folder ./output --no-test
       - name: Test conda package
-        continue-on-error: ${{ github.ref_name != github.event.repository.default_branch}}
         working-directory: ./build/output
         run: |
           export CONDA_SUBDIR="${{ runner.os == 'macOS' && 'osx-arm64' || (runner.os == 'Windows' && 'win-64' || 'linux-64') }}"
-          conda build --test --override-channels -c esri -c esri-build -c defaults $CONDA_SUBDIR/*.conda
+          export ARCGIS_CONDA_PKG=$(find $CONDA_SUBDIR -name "*.conda")
+          conda build --test --override-channels -c esri -c esri-build -c defaults $ARCGIS_CONDA_PKG || {
+            # test failure is a warning
+            echo "::warning file=$ARCGIS_CONDA_PKG::Conda package test failed. Please review the logs."
+          }
       - name: Convert conda package
         # convert to osx-arm64 to osx-64
         if: ${{ runner.os == 'macOS' }}
